### ISSUE TITLE
Random Python suggestions

### ISSUE THREAD

**Issue by sethtroisi** [f0lg0/geneticAlgorithm-1#5]
I've had this in my TODO list to give some feedback (after you asked on reddit).

Couple of random notes

---

Prefer `range` when you know how many times the loop will run
https://github.com/f0lg0/geneticAlgorithm-1/blob/master/src/main.py#L42-L45 and several other places
```
for i in range(size):
	self._population.append(Individual())
```

---

`pop.getPopulation()[random.randrange(0, POPULATION_SIZE)]`
See `random.choice()`

---

```
for i in range(len(TARGET)):
			if i < midpoint:
				child.getDNA()[i] = parentA.getDNA()[i]
			else:
				child.getDNA()[i] = parentB.getDNA()[i]
```

This can be replaced with a couple of different things all of which should be faster

```
child.getDNA()[:midpoint] = parentA.getDNA()[:midpoint]
child.getDNA()[midpoint:] = parentB.getDNA()[midpoint:]
```
or
```
child.getDNA()[:] = parentA.getDNA()[:midpoint] + parentB.getDNA()[midpoint:]
```

---

```
for x in pop.getPopulation():
			if random.random() <= MUTATION_RATE:
				x.getDNA()[random.randrange(0, INDIVIDUAL_SIZE)] = random.choice(KEYS)
```
This loop runs `population` times and calls random.random() each time.
if `population` is large (maybe 100+) it would be faster to write something like this which is very similar but involves much fewer calls to random. This probably is not a bottleneck but it can still be good practice to thing about these things.

```
popSize = len(pop.getPopulation())
mutations = random.gauss(MUTATION_RATE * popSize, 2)
for x in random.choices(pop.getPopulation(), k=popSize):
    x.getDNA()[random.randrange(0, INDIVIDUAL_SIZE)] = random.choice(KEYS)
```

---

It's sometimes a code smell to have code in the format

```
SETUP
BLOCK A

for / while loop:
    BLOCK A
```

the initial `BLOCK A` is sometimes a little different because of setup but often it can be tweaked to be of the form 

```
SETUP
for / while loop:
    BLOCK A
```

This can be bad if BLOCK A involves complicated calls that you always have to remember to changed both of.

here
```
	population = Population(POPULATION_SIZE)
	population.getPopulation().sort(key = lambda x: x.fitness, reverse = True)
	printPopulation(population, 0)

	algo = GeneticAlgorithm()

	generationNumber = 1
	while population.getPopulation()[0].fitness < 1:
		algo.evolve(population)
		population.getPopulation().sort(key = lambda x: x.fitness, reverse = True)
		printPopulation(population, generationNumber)
		generationNumber += 1
```

I think this is equivilant to

```
    population = Population(POPULATION_SIZE)
    algo = GeneticAlgorithm()

    generationNumber = 0
    while True:
	population.getPopulation().sort(key = lambda x: x.fitness, reverse = True)
        printPopulation(population, generationNumber)

        if population.getPopulation()[0].fitness >= 1:
            break

	algo.evolve(population)
```

**Comment by f0lg0** [comment]
@sethtroisi 
Thanks for your nice suggestions. I haven't touched this code for a long time, it was my first ever project with Python.I recognized almost all of the things that you suggested while I was looking at my code after your issue. I'm planning on studying python basics again to write more pythonic code. I'm pretty busy with other projects so I'll probably leave this code as it is until I finish all the pending projects. Thank you so much!

**Comment by sethtroisi** [comment]
It only took a couple of minutes to write up.

Good luck learning more python. If you ever want a review of other code feel free to @ me.

**Comment by f0lg0** [comment]
@sethtroisi 
Oh okay! I will look at it then. Thanks again!
i've noticed only a thing: like in the loop where you suggest to use range "i" is unused. Is it a problem in Python?
`		for i in range(size):
			self._population.append(Individual())`

**Comment by f0lg0** [comment]
@sethtroisi 
So, I've looked up at the things you suggested and as I said before they made a lot of sense even to me after looking at the code. Pushed all of them except for this:
```
popSize = len(pop.getPopulation())
mutations = random.gauss(MUTATION_RATE * popSize, 2)
for x in random.choices(pop.getPopulation(), k=popSize):
    x.getDNA()[random.randrange(0, INDIVIDUAL_SIZE)] = random.choice(KE
```

Just because I don't know the guass function and I would like to look at it before adding it to the code. I don't wanna copy and paste and forget about it :)

Anyway, thank you again for the advice and the time you spent working on my really crappy first project in Python haha. I wonder why you decided to give me advice after all this time :D

**Comment by sethtroisi** [comment]
It's not uncommon to use `i` for the loop even if i is unused.
Maybe slightly more correct is to use `_` for an unused loop variable e.g.
`for _ in range(size):`
or
`for firstName, _ in [("frank", "smith"), ("bob", "johnson"), ("sarah", "silver")]:`

**Comment by sethtroisi** [comment]
the `gauss` change calls upon some stats knowledge instead of python.

let's image that popSize is 100 and MUTATION_RATE = 1/10
then we expect that 
```
count = 0
for x in pop.getPopulation():
    if random.random() <= MUTATION_RATE:
        count += 1
```
count should be around 100 * 1/10 = 10.
but it won't always be 10. 

sometimes the original code will mutate all items ((1/10) ^ 100 = 1 in a googol times)
sometimes it will mutate no items ((9/10)^ 100 = 2 in a million times)
sometimes it will change 10 items. ((100 choose 10) * (1/10) ^ 10 * (9/10) ^ 90 = 1 in 7 times ))

we can choose to always change 10
`for x in random.choices(pop.getPopulation(), k=10)`
or we can use guass to get a number near 10 with some distribution. 

I modeled what's going on in [colab](https://colab.research.google.com/drive/1DWCLlpvz3Yr8lmmMveKP3yzhFfff9x01#scrollTo=DaCSw65nWNIy) if you want to see.

I'm actually hesitant about the suggestion now. your code is much more descriptive and my suggestion is only faster in the case that both popSize is large and MUTATION_RATE is low.

**Comment by f0lg0** [comment]
Perfect! thanks :)
